### ISSUE TITLE
Documentation for GET /journeys/legs/:ref wrong?

### ISSUE THREAD

**Issue by patrickj0607** [derhuerst/vbb-client#8]
The example of section [```GET /journeys/legs/:ref```](https://github.com/derhuerst/vbb-rest/blob/2/docs/index.md#get-journeyslegsref) in the documentation states _# this won't work, get a new ref from /journeys first_. But I cannot see a ref in the received data of ```GET /journeys```. 

However, the [```GET /stations/:id/departures```](https://github.com/derhuerst/vbb-rest/blob/2/docs/index.md#get-stationsiddepartures) gives me a ```journeyID``` which looks quite similar to the expected ref string.

Is that just a mistake in the documentation or am I doing something wrong?

**Comment by derhuerst** [comment]
General explanation: `vbb-rest` just responds with the data returned by [`hafas-client`](https://github.com/public-transport/hafas-client). I didn't duplicate documentation about the response format because I would quickly forget to update the other if I changed one of them. This is why you currently need to read the `hafas-client` docs as well. **I think that this is a suboptimal solution though.**

Specific explanation: As mentioned in [the docs for `require('hafas-client').journeys()`](https://github.com/public-transport/hafas-client/blob/master/docs/journeys.md#journeysfrom-to-opt), each `journey` leg has an `id` field, which you can pass into `/journeys/legs/:ref`. It basically works like [the docs for `require('hafas-client').journeyLeg(ref)`](https://github.com/public-transport/hafas-client/blob/master/docs/journey-leg.md#journeylegref-linename-opt).

**Comment by derhuerst** [comment]
please reopen if you still have a question regarding this.
